const express = require('express')
const router = express.Router();
const { v4: uuid } = require('uuid');
const firebase = require('../fbConfig');

const db = firebase.firestore();

/**
 * Res: {
 *   postID1: {}, postID2: {}, ...
 * }
 */
router.get("/", (req, res) => {
  console.log("GET to /api/posts received");
  db.collection("posts").get()
  .then((querySnapshot) => {
    let result = {};
    // doc.data() is never undefined for query doc snapshots
    querySnapshot.forEach((doc) => {
      result[doc.id] = doc.data();
    });
    // return a JSON
    res.status(200).send(result);
  })
  .catch((error) => {
    console.log(error);
    res.status(404).send("Failed to get posts")
  })
});

/**
 * req.body
 * 
 * Res: the postID generated by Firestore
 */
router.post("/", (req, res) => {
  console.log("POST to /api/posts received");
  console.log(req.body);
  // let firebase generate ID
  db.collection("posts").add(req.body)
  .then((docRef) => {
    console.log("New postID: " + docRef.id);
    res.status(201).send(docRef.id);
  })
  .catch(error => {
    console.log(error);
    res.status(404).send("Failed to add post")
  })
});

/**
 * req.query.postID
 * req.body
 * 
 * Res: No response
 */
router.put("/", (req, res) => {
  console.log("PUT to /api/posts received");
  console.log(req);
  console.log(req.query.postID);
  console.log(req.body);

  const postID = req.query.postID;
  db.collection("posts").doc(postID).update(req.body)
  .then(() => {
    console.log("Post update complete");
    res.status(200).send();
  })
  .catch(error => {
    console.log(error);
    res.status(404).send("Failed to update post")
  })
});

/**
 * req.query.postID
 * 
 * Res: No response
 */
router.delete("/", (req, res) => {
  console.log("DELETE to /api/posts received");
  console.log(req.query.postID);

  const postID = req.query.postID;
  db.collection("posts").doc(postID).delete()
  .then(() => {
    console.log("Delete complete");
    res.status(200).send();
  })
  .catch(error => {
    console.log(error);
    res.status(404).send("Failed to delete post")
  })
});

module.exports = router;