export const ACTION_TYPES = {
  GET_POSTS: "GET_POSTS",
  POST_POST: "POST_POST",
  DELETE_POST: "DELETE_POST",
  MODIFY_POST: "MODIFY_POST",

  GET_COMMENTS: "GET_COMMENTS",
  POST_COMMENTS: "POST_COMMENTS",
  DELETE_COMMENTS: "DELETE_COMMENTS",
  MODIFY_COMMENTS: "MODIFY_COMMENTS",

  CLEAR_COMMENTS:" CLEAR_COMMENTS",


  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  INVALID_LOGIN: "INVALID_LOGIN",
  SIGN_UP:"SIGN_UP",
  LOGIN_NETWORK_ERROR: "LOGIN_NETWORK_ERROR",
  LOGOUT: "LOGOUT",
  UPDATE_ERR_MSG: "UPDATE_ERR_MSG",


};